// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Categories: typeof import('./components/categories.vue')['default']
    Navigation: typeof import('./components/navigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Signin: typeof import('./components/signin.vue')['default']
    Signup: typeof import('./components/signup.vue')['default']
  }
}
